# -*- coding: utf-8 -*-
"""module_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QY0zf-yBrHEtqRnw-4FqRPk4RjeK0uWt

**Módulo 1 - Váriaveis & Tipos de Dados**
- Aula 5: Booleanos

**Meu Primeiro código**
"""

print("Olá, mundo!")