# -*- coding: utf-8 -*-
"""module_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QY0zf-yBrHEtqRnw-4FqRPk4RjeK0uWt

**Módulo 1 - Váriaveis & Tipos de Dados**
- Aula 2: Váriaveis

**Tipos de Váriaveis**
"""

idade = 30
print(idade)

idade = 27
print(idade)

nome = "Bruno"
print(nome)

"""**Tipos Numéricos:** Inteiros (int) e Real (float)"""

preco_do_xbox = 4000
tipo_preco = type(preco_do_xbox)

print(preco_do_xbox)
print(tipo_preco)

juros = 0.55
tipo_juros = type(juros)

print(juros)
print(tipo_juros)

"""**Tipos de Texto:** strings (str)"""

primeiro_nome = "Bruno"
print(primeiro_nome)
print(type(primeiro_nome))

estado = 'Rio de Janeiro'
print(estado)
print(type(estado))

"""**Tipos lógicos:** booleanos (bool)"""

usuario_maior_de_idade = True

print(usuario_maior_de_idade)
print(type(usuario_maior_de_idade))

"""**Tipo vazio:** (NoneType)"""

telefone_fixo = None

print(telefone_fixo)
print(type(telefone_fixo))